/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppMesasRouteImport } from './routes/_app/mesas'
import { Route as AppHistoricoRouteImport } from './routes/_app/historico'
import { Route as AppEntregasRouteImport } from './routes/_app/entregas'
import { Route as AppEmpresasRouteImport } from './routes/_app/empresas'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCozinhaRouteImport } from './routes/_app/cozinha'
import { Route as AppCombosRouteImport } from './routes/_app/combos'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppAdicionaisRouteImport } from './routes/_app/adicionais'
import { Route as AppPedidosIndexRouteImport } from './routes/_app/pedidos/index'
import { Route as AppPedidosNovoRouteImport } from './routes/_app/pedidos/novo'
import { Route as AppPedidosIdRouteImport } from './routes/_app/pedidos/$id'
import { Route as AppMesasIdRouteImport } from './routes/_app/mesas/$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppMesasRoute = AppMesasRouteImport.update({
  id: '/mesas',
  path: '/mesas',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppEntregasRoute = AppEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCozinhaRoute = AppCozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => AppRoute,
} as any)
const AppCombosRoute = AppCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppAdicionaisRoute = AppAdicionaisRouteImport.update({
  id: '/adicionais',
  path: '/adicionais',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosIndexRoute = AppPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosNovoRoute = AppPedidosNovoRouteImport.update({
  id: '/pedidos/novo',
  path: '/pedidos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosIdRoute = AppPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMesasIdRoute = AppMesasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMesasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/adicionais': typeof AppAdicionaisRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/combos': typeof AppCombosRoute
  '/cozinha': typeof AppCozinhaRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/entregas': typeof AppEntregasRoute
  '/historico': typeof AppHistoricoRoute
  '/mesas': typeof AppMesasRouteWithChildren
  '/produtos': typeof AppProdutosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/mesas/$id': typeof AppMesasIdRoute
  '/pedidos/$id': typeof AppPedidosIdRoute
  '/pedidos/novo': typeof AppPedidosNovoRoute
  '/pedidos/': typeof AppPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/adicionais': typeof AppAdicionaisRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/combos': typeof AppCombosRoute
  '/cozinha': typeof AppCozinhaRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/entregas': typeof AppEntregasRoute
  '/historico': typeof AppHistoricoRoute
  '/mesas': typeof AppMesasRouteWithChildren
  '/produtos': typeof AppProdutosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/mesas/$id': typeof AppMesasIdRoute
  '/pedidos/$id': typeof AppPedidosIdRoute
  '/pedidos/novo': typeof AppPedidosNovoRoute
  '/pedidos': typeof AppPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/adicionais': typeof AppAdicionaisRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/combos': typeof AppCombosRoute
  '/_app/cozinha': typeof AppCozinhaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/entregas': typeof AppEntregasRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/mesas': typeof AppMesasRouteWithChildren
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/mesas/$id': typeof AppMesasIdRoute
  '/_app/pedidos/$id': typeof AppPedidosIdRoute
  '/_app/pedidos/novo': typeof AppPedidosNovoRoute
  '/_app/pedidos/': typeof AppPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/adicionais'
    | '/categorias'
    | '/clientes'
    | '/combos'
    | '/cozinha'
    | '/dashboard'
    | '/empresas'
    | '/entregas'
    | '/historico'
    | '/mesas'
    | '/produtos'
    | '/usuarios'
    | '/mesas/$id'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/adicionais'
    | '/categorias'
    | '/clientes'
    | '/combos'
    | '/cozinha'
    | '/dashboard'
    | '/empresas'
    | '/entregas'
    | '/historico'
    | '/mesas'
    | '/produtos'
    | '/usuarios'
    | '/mesas/$id'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/adicionais'
    | '/_app/categorias'
    | '/_app/clientes'
    | '/_app/combos'
    | '/_app/cozinha'
    | '/_app/dashboard'
    | '/_app/empresas'
    | '/_app/entregas'
    | '/_app/historico'
    | '/_app/mesas'
    | '/_app/produtos'
    | '/_app/usuarios'
    | '/_app/mesas/$id'
    | '/_app/pedidos/$id'
    | '/_app/pedidos/novo'
    | '/_app/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesas': {
      id: '/_app/mesas'
      path: '/mesas'
      fullPath: '/mesas'
      preLoaderRoute: typeof AppMesasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entregas': {
      id: '/_app/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AppEntregasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cozinha': {
      id: '/_app/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof AppCozinhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/combos': {
      id: '/_app/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof AppCombosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adicionais': {
      id: '/_app/adicionais'
      path: '/adicionais'
      fullPath: '/adicionais'
      preLoaderRoute: typeof AppAdicionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos/': {
      id: '/_app/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AppPedidosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos/novo': {
      id: '/_app/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AppPedidosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos/$id': {
      id: '/_app/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AppPedidosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesas/$id': {
      id: '/_app/mesas/$id'
      path: '/$id'
      fullPath: '/mesas/$id'
      preLoaderRoute: typeof AppMesasIdRouteImport
      parentRoute: typeof AppMesasRoute
    }
  }
}

interface AppMesasRouteChildren {
  AppMesasIdRoute: typeof AppMesasIdRoute
}

const AppMesasRouteChildren: AppMesasRouteChildren = {
  AppMesasIdRoute: AppMesasIdRoute,
}

const AppMesasRouteWithChildren = AppMesasRoute._addFileChildren(
  AppMesasRouteChildren,
)

interface AppRouteChildren {
  AppAdicionaisRoute: typeof AppAdicionaisRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCombosRoute: typeof AppCombosRoute
  AppCozinhaRoute: typeof AppCozinhaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppEntregasRoute: typeof AppEntregasRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppMesasRoute: typeof AppMesasRouteWithChildren
  AppProdutosRoute: typeof AppProdutosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppPedidosIdRoute: typeof AppPedidosIdRoute
  AppPedidosNovoRoute: typeof AppPedidosNovoRoute
  AppPedidosIndexRoute: typeof AppPedidosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdicionaisRoute: AppAdicionaisRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppClientesRoute: AppClientesRoute,
  AppCombosRoute: AppCombosRoute,
  AppCozinhaRoute: AppCozinhaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppEntregasRoute: AppEntregasRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppMesasRoute: AppMesasRouteWithChildren,
  AppProdutosRoute: AppProdutosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppPedidosIdRoute: AppPedidosIdRoute,
  AppPedidosNovoRoute: AppPedidosNovoRoute,
  AppPedidosIndexRoute: AppPedidosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
