/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppProdutosRouteImport } from './routes/_app/produtos'
import { Route as AppMensagensRouteImport } from './routes/_app/mensagens'
import { Route as AppHistoricoRouteImport } from './routes/_app/historico'
import { Route as AppEntregasRouteImport } from './routes/_app/entregas'
import { Route as AppEmpresasRouteImport } from './routes/_app/empresas'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCozinhaRouteImport } from './routes/_app/cozinha'
import { Route as AppConectoresRouteImport } from './routes/_app/conectores'
import { Route as AppCombosRouteImport } from './routes/_app/combos'
import { Route as AppClientesRouteImport } from './routes/_app/clientes'
import { Route as AppChamadosRouteImport } from './routes/_app/chamados'
import { Route as AppCategoriasRouteImport } from './routes/_app/categorias'
import { Route as AppCardapioRouteImport } from './routes/_app/cardapio'
import { Route as AppAdicionaisRouteImport } from './routes/_app/adicionais'
import { Route as AppSuporteIndexRouteImport } from './routes/_app/suporte/index'
import { Route as AppPedidosIndexRouteImport } from './routes/_app/pedidos/index'
import { Route as AppMesasIndexRouteImport } from './routes/_app/mesas/index'
import { Route as ImprimirPedidoIdRouteImport } from './routes/imprimir/pedido.$id'
import { Route as ImprimirMesaIdRouteImport } from './routes/imprimir/mesa.$id'
import { Route as AppSuporteIdRouteImport } from './routes/_app/suporte/$id'
import { Route as AppPedidosNovoRouteImport } from './routes/_app/pedidos/novo'
import { Route as AppPedidosIdRouteImport } from './routes/_app/pedidos/$id'
import { Route as AppMesasIdRouteImport } from './routes/_app/mesas/$id'
import { Route as ApiPublicWebhooksWhatsappRouteImport } from './routes/api/public/webhooks/whatsapp'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppMensagensRoute = AppMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppEntregasRoute = AppEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCozinhaRoute = AppCozinhaRouteImport.update({
  id: '/cozinha',
  path: '/cozinha',
  getParentRoute: () => AppRoute,
} as any)
const AppConectoresRoute = AppConectoresRouteImport.update({
  id: '/conectores',
  path: '/conectores',
  getParentRoute: () => AppRoute,
} as any)
const AppCombosRoute = AppCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppChamadosRoute = AppChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCardapioRoute = AppCardapioRouteImport.update({
  id: '/cardapio',
  path: '/cardapio',
  getParentRoute: () => AppRoute,
} as any)
const AppAdicionaisRoute = AppAdicionaisRouteImport.update({
  id: '/adicionais',
  path: '/adicionais',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteIndexRoute = AppSuporteIndexRouteImport.update({
  id: '/suporte/',
  path: '/suporte/',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosIndexRoute = AppPedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => AppRoute,
} as any)
const AppMesasIndexRoute = AppMesasIndexRouteImport.update({
  id: '/mesas/',
  path: '/mesas/',
  getParentRoute: () => AppRoute,
} as any)
const ImprimirPedidoIdRoute = ImprimirPedidoIdRouteImport.update({
  id: '/imprimir/pedido/$id',
  path: '/imprimir/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirMesaIdRoute = ImprimirMesaIdRouteImport.update({
  id: '/imprimir/mesa/$id',
  path: '/imprimir/mesa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuporteIdRoute = AppSuporteIdRouteImport.update({
  id: '/suporte/$id',
  path: '/suporte/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosNovoRoute = AppPedidosNovoRouteImport.update({
  id: '/pedidos/novo',
  path: '/pedidos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppPedidosIdRoute = AppPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMesasIdRoute = AppMesasIdRouteImport.update({
  id: '/mesas/$id',
  path: '/mesas/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhooksWhatsappRoute =
  ApiPublicWebhooksWhatsappRouteImport.update({
    id: '/api/public/webhooks/whatsapp',
    path: '/api/public/webhooks/whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/adicionais': typeof AppAdicionaisRoute
  '/cardapio': typeof AppCardapioRoute
  '/categorias': typeof AppCategoriasRoute
  '/chamados': typeof AppChamadosRoute
  '/clientes': typeof AppClientesRoute
  '/combos': typeof AppCombosRoute
  '/conectores': typeof AppConectoresRoute
  '/cozinha': typeof AppCozinhaRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/entregas': typeof AppEntregasRoute
  '/historico': typeof AppHistoricoRoute
  '/mensagens': typeof AppMensagensRoute
  '/produtos': typeof AppProdutosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/mesas/$id': typeof AppMesasIdRoute
  '/pedidos/$id': typeof AppPedidosIdRoute
  '/pedidos/novo': typeof AppPedidosNovoRoute
  '/suporte/$id': typeof AppSuporteIdRoute
  '/imprimir/mesa/$id': typeof ImprimirMesaIdRoute
  '/imprimir/pedido/$id': typeof ImprimirPedidoIdRoute
  '/mesas/': typeof AppMesasIndexRoute
  '/pedidos/': typeof AppPedidosIndexRoute
  '/suporte/': typeof AppSuporteIndexRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/adicionais': typeof AppAdicionaisRoute
  '/cardapio': typeof AppCardapioRoute
  '/categorias': typeof AppCategoriasRoute
  '/chamados': typeof AppChamadosRoute
  '/clientes': typeof AppClientesRoute
  '/combos': typeof AppCombosRoute
  '/conectores': typeof AppConectoresRoute
  '/cozinha': typeof AppCozinhaRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/entregas': typeof AppEntregasRoute
  '/historico': typeof AppHistoricoRoute
  '/mensagens': typeof AppMensagensRoute
  '/produtos': typeof AppProdutosRoute
  '/usuarios': typeof AppUsuariosRoute
  '/mesas/$id': typeof AppMesasIdRoute
  '/pedidos/$id': typeof AppPedidosIdRoute
  '/pedidos/novo': typeof AppPedidosNovoRoute
  '/suporte/$id': typeof AppSuporteIdRoute
  '/imprimir/mesa/$id': typeof ImprimirMesaIdRoute
  '/imprimir/pedido/$id': typeof ImprimirPedidoIdRoute
  '/mesas': typeof AppMesasIndexRoute
  '/pedidos': typeof AppPedidosIndexRoute
  '/suporte': typeof AppSuporteIndexRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/adicionais': typeof AppAdicionaisRoute
  '/_app/cardapio': typeof AppCardapioRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/chamados': typeof AppChamadosRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/combos': typeof AppCombosRoute
  '/_app/conectores': typeof AppConectoresRoute
  '/_app/cozinha': typeof AppCozinhaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/entregas': typeof AppEntregasRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/mensagens': typeof AppMensagensRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/mesas/$id': typeof AppMesasIdRoute
  '/_app/pedidos/$id': typeof AppPedidosIdRoute
  '/_app/pedidos/novo': typeof AppPedidosNovoRoute
  '/_app/suporte/$id': typeof AppSuporteIdRoute
  '/imprimir/mesa/$id': typeof ImprimirMesaIdRoute
  '/imprimir/pedido/$id': typeof ImprimirPedidoIdRoute
  '/_app/mesas/': typeof AppMesasIndexRoute
  '/_app/pedidos/': typeof AppPedidosIndexRoute
  '/_app/suporte/': typeof AppSuporteIndexRoute
  '/api/public/webhooks/whatsapp': typeof ApiPublicWebhooksWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/adicionais'
    | '/cardapio'
    | '/categorias'
    | '/chamados'
    | '/clientes'
    | '/combos'
    | '/conectores'
    | '/cozinha'
    | '/dashboard'
    | '/empresas'
    | '/entregas'
    | '/historico'
    | '/mensagens'
    | '/produtos'
    | '/usuarios'
    | '/mesas/$id'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/suporte/$id'
    | '/imprimir/mesa/$id'
    | '/imprimir/pedido/$id'
    | '/mesas/'
    | '/pedidos/'
    | '/suporte/'
    | '/api/public/webhooks/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/adicionais'
    | '/cardapio'
    | '/categorias'
    | '/chamados'
    | '/clientes'
    | '/combos'
    | '/conectores'
    | '/cozinha'
    | '/dashboard'
    | '/empresas'
    | '/entregas'
    | '/historico'
    | '/mensagens'
    | '/produtos'
    | '/usuarios'
    | '/mesas/$id'
    | '/pedidos/$id'
    | '/pedidos/novo'
    | '/suporte/$id'
    | '/imprimir/mesa/$id'
    | '/imprimir/pedido/$id'
    | '/mesas'
    | '/pedidos'
    | '/suporte'
    | '/api/public/webhooks/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_app/adicionais'
    | '/_app/cardapio'
    | '/_app/categorias'
    | '/_app/chamados'
    | '/_app/clientes'
    | '/_app/combos'
    | '/_app/conectores'
    | '/_app/cozinha'
    | '/_app/dashboard'
    | '/_app/empresas'
    | '/_app/entregas'
    | '/_app/historico'
    | '/_app/mensagens'
    | '/_app/produtos'
    | '/_app/usuarios'
    | '/_app/mesas/$id'
    | '/_app/pedidos/$id'
    | '/_app/pedidos/novo'
    | '/_app/suporte/$id'
    | '/imprimir/mesa/$id'
    | '/imprimir/pedido/$id'
    | '/_app/mesas/'
    | '/_app/pedidos/'
    | '/_app/suporte/'
    | '/api/public/webhooks/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ImprimirMesaIdRoute: typeof ImprimirMesaIdRoute
  ImprimirPedidoIdRoute: typeof ImprimirPedidoIdRoute
  ApiPublicWebhooksWhatsappRoute: typeof ApiPublicWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mensagens': {
      id: '/_app/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AppMensagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entregas': {
      id: '/_app/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AppEntregasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cozinha': {
      id: '/_app/cozinha'
      path: '/cozinha'
      fullPath: '/cozinha'
      preLoaderRoute: typeof AppCozinhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conectores': {
      id: '/_app/conectores'
      path: '/conectores'
      fullPath: '/conectores'
      preLoaderRoute: typeof AppConectoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/combos': {
      id: '/_app/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof AppCombosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chamados': {
      id: '/_app/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof AppChamadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cardapio': {
      id: '/_app/cardapio'
      path: '/cardapio'
      fullPath: '/cardapio'
      preLoaderRoute: typeof AppCardapioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adicionais': {
      id: '/_app/adicionais'
      path: '/adicionais'
      fullPath: '/adicionais'
      preLoaderRoute: typeof AppAdicionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suporte/': {
      id: '/_app/suporte/'
      path: '/suporte'
      fullPath: '/suporte/'
      preLoaderRoute: typeof AppSuporteIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos/': {
      id: '/_app/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AppPedidosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesas/': {
      id: '/_app/mesas/'
      path: '/mesas'
      fullPath: '/mesas/'
      preLoaderRoute: typeof AppMesasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/imprimir/pedido/$id': {
      id: '/imprimir/pedido/$id'
      path: '/imprimir/pedido/$id'
      fullPath: '/imprimir/pedido/$id'
      preLoaderRoute: typeof ImprimirPedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir/mesa/$id': {
      id: '/imprimir/mesa/$id'
      path: '/imprimir/mesa/$id'
      fullPath: '/imprimir/mesa/$id'
      preLoaderRoute: typeof ImprimirMesaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/suporte/$id': {
      id: '/_app/suporte/$id'
      path: '/suporte/$id'
      fullPath: '/suporte/$id'
      preLoaderRoute: typeof AppSuporteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos/novo': {
      id: '/_app/pedidos/novo'
      path: '/pedidos/novo'
      fullPath: '/pedidos/novo'
      preLoaderRoute: typeof AppPedidosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pedidos/$id': {
      id: '/_app/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AppPedidosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mesas/$id': {
      id: '/_app/mesas/$id'
      path: '/mesas/$id'
      fullPath: '/mesas/$id'
      preLoaderRoute: typeof AppMesasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhooks/whatsapp': {
      id: '/api/public/webhooks/whatsapp'
      path: '/api/public/webhooks/whatsapp'
      fullPath: '/api/public/webhooks/whatsapp'
      preLoaderRoute: typeof ApiPublicWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdicionaisRoute: typeof AppAdicionaisRoute
  AppCardapioRoute: typeof AppCardapioRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppChamadosRoute: typeof AppChamadosRoute
  AppClientesRoute: typeof AppClientesRoute
  AppCombosRoute: typeof AppCombosRoute
  AppConectoresRoute: typeof AppConectoresRoute
  AppCozinhaRoute: typeof AppCozinhaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppEntregasRoute: typeof AppEntregasRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppMensagensRoute: typeof AppMensagensRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppMesasIdRoute: typeof AppMesasIdRoute
  AppPedidosIdRoute: typeof AppPedidosIdRoute
  AppPedidosNovoRoute: typeof AppPedidosNovoRoute
  AppSuporteIdRoute: typeof AppSuporteIdRoute
  AppMesasIndexRoute: typeof AppMesasIndexRoute
  AppPedidosIndexRoute: typeof AppPedidosIndexRoute
  AppSuporteIndexRoute: typeof AppSuporteIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdicionaisRoute: AppAdicionaisRoute,
  AppCardapioRoute: AppCardapioRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppChamadosRoute: AppChamadosRoute,
  AppClientesRoute: AppClientesRoute,
  AppCombosRoute: AppCombosRoute,
  AppConectoresRoute: AppConectoresRoute,
  AppCozinhaRoute: AppCozinhaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppEntregasRoute: AppEntregasRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppMensagensRoute: AppMensagensRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppMesasIdRoute: AppMesasIdRoute,
  AppPedidosIdRoute: AppPedidosIdRoute,
  AppPedidosNovoRoute: AppPedidosNovoRoute,
  AppSuporteIdRoute: AppSuporteIdRoute,
  AppMesasIndexRoute: AppMesasIndexRoute,
  AppPedidosIndexRoute: AppPedidosIndexRoute,
  AppSuporteIndexRoute: AppSuporteIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ImprimirMesaIdRoute: ImprimirMesaIdRoute,
  ImprimirPedidoIdRoute: ImprimirPedidoIdRoute,
  ApiPublicWebhooksWhatsappRoute: ApiPublicWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
